### ISSUE TITLE
download link has been missing

### ISSUE THREAD

**Issue by zfxSteven** [UCSD-AI4H/Medical-Dialogue-System#2]
download link has been missing

**Comment by jkooy** [comment]
Hi, which one are you referring to? I checked both two are there.

**Comment by zfxSteven** [comment]
> Hi, which one are you referring to? I checked both two are there.

sorry，昨天google服务出现短暂的不可用，好像让我赶上了。今天试了试，所有文件都可以。谢谢你的 及时回复

**Comment by Tommy7013** [comment]
> > Hi, which one are you referring to? I checked both two are there.
> 
> sorry，昨天google服务出现短暂的不可用，好像让我赶上了。今天试了试，所有文件都可以。谢谢你的 及时回复

could you share the train_data.json,test_data.json?
