### ISSUE TITLE
请问gpt2的预训练模型在哪里可以获取

### ISSUE THREAD

**Issue by rorsarach** [UCSD-AI4H/Medical-Dialogue-System#3]

**Comment by LeiShenVictoria** [comment]
Same question here!
How to get the pre-trained models (gpt and bert-gpt)~
Thx

**Comment by rorsarach** [comment]
Maybe we should use code to pre-trained it.
I think&nbsp;GPT2-chitchat&nbsp;&nbsp;could be useful.
Maybe this models will be provided by&nbsp;DialoGPT&nbsp;.
I'm tring gpt2-chitchar to get a model.
If u have any advice,thx.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UCSD-AI4H/Medical-Dialogue-System"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 下午3:55
收件人:&nbsp;"UCSD-AI4H/Medical-Dialogue-System"<Medical-Dialogue-System@noreply.github.com&gt;;
抄送:&nbsp;"独自一人。"<xieguanyue@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [UCSD-AI4H/Medical-Dialogue-System] 请问gpt2的预训练模型在哪里可以获取 (#3)





 
Same question here!
 How to get the pre-trained models (gpt and bert-gpt)~
 Thx

**Comment by jkooy** [comment]
Hi, the pre-trained models has been updated.
